import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Projedata Interview Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt_br">
      <body className="antialised w-screen h-screen overflow-x-hidden overflow-y-auto">
        {children}
      </body>
    </html>
  );
}
